AllCops:
  Exclude:
    - lib/fandom-word.rb

Layout/EndOfLine:
  Exclude:
    - fandom-word.gemspec
    - Gemfile
    - Rakefile
    - lib/**/*
    - spec/**/*

Metrics/BlockLength:
    Exclude:
      - spec/**/*

Metrics/LineLength:
  Max: 120
